version: "3"

services:
  rebbitmq:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db_migrate:
    build: .
    # command: bash -c "python tasks.py"
    depends_on:
      - db
    healthcheck:
      timeout: 10s

#  vk_to_telegram_bot:
#    build: .
#    restart: always
#    depends_on:
#      - db
#      - db_migrate

  celery_beat:
    build: .
    command: "celery -A celeryapp:app beat"
    restart: always
    depends_on:
      - db

  celery_worker:
    build: .
    command: "celery -A celeryapp:app worker -l INFO --pool=solo"
    restart: always
    depends_on:
      - db