version: "3.9"

services:
  rebbitmq:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vk_to_telegram_bot:
    build: .
    command: "python main.py"
    restart: always
    depends_on:
      - db

  celery_beat:
    build: .
    command: "celery -A celeryapp:app beat"
    restart: always
    depends_on:
      - db

  celery_worker:
    build: .
    command: "celery -A celeryapp:app worker -l INFO --pool=solo"
    restart: always
    depends_on:
      - db